version: '2.1'

services:

  zookeeper:
    hostname: zookeeper
    container_name: zookeeper
    image: quay.io/strimzi/kafka:0.32.0-kafka-3.3.1
    command: [
      "sh", "-c",
      "bin/zookeeper-server-start.sh config/zookeeper.properties"
    ]
    ports:
      - 2181:2181
    environment:
      LOG_DIR: /tmp/logs
    networks:
      - demo-network

  kafka:
    hostname: kafka
    container_name: kafka
    image: quay.io/strimzi/kafka:0.32.0-kafka-3.3.1
    command: [
      "sh", "-c",
      "bin/kafka-server-start.sh config/server.properties --override inter.broker.listener.name=$${KAFKA_INTER_BROKER_LISTENER_NAME} --override listener.security.protocol.map=$${KAFKA_LISTENER_SECURITY_PROTOCOL_MAP} --override listeners=$${KAFKA_LISTENERS} --override advertised.listeners=$${KAFKA_ADVERTISED_LISTENERS} --override zookeeper.connect=$${KAFKA_ZOOKEEPER_CONNECT} --override num.partitions=$${KAFKA_NUM_PARTITIONS} --override group.min.session.timeout.ms=$${KAFKA_GROUP_MIN_SESSION_TIMEOUT_MS}"
    ]
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
      - 29092:29092
    environment:
      LOG_DIR: /tmp/logs
      KAFKA_ADVERTISED_LISTENERS: DOCKER_INSIDE://kafka:9092,DOCKER_OUTSIDE://localhost:29092
      KAFKA_LISTENERS: DOCKER_INSIDE://kafka:9092,DOCKER_OUTSIDE://0.0.0.0:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: DOCKER_INSIDE:PLAINTEXT,DOCKER_OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER_INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_GROUP_MIN_SESSION_TIMEOUT_MS: 250
      KAFKA_NUM_PARTITIONS: 1
    networks:
      - demo-network

networks:
  demo-network:
    name: kafka-tutorial